version: '3.7'
services:
  config-server:
    image: config-server
    ports:
      - "8888:8888"
    restart: always
    networks:
      - spring
  eureka-server:
      image: eureka-server
      ports:
        - "8761:8761"
      restart: always
      networks:
        - spring
networks:
  spring:
    