INSERT INTO products (NAME,PRICE,CREATED_AT) VALUES ('Panasonic', 800, NOW());
INSERT INTO products (NAME,PRICE,CREATED_AT) VALUES ('Sony', 500, NOW());
INSERT INTO products (NAME,PRICE,CREATED_AT) VALUES ('Apple', 2500, NOW());
INSERT INTO products (NAME,PRICE,CREATED_AT) VALUES ('Xiomi', 1500, NOW());