INSERT INTO USERS (USERNAME,PASSWORD,ENABLED,NAME,LASTNAME,EMAIL) VALUES ('Andres', '12345', 1, 'Andres', 'Montoya', 'andres@correo.com');
INSERT INTO USERS (USERNAME,PASSWORD,ENABLED,NAME,LASTNAME,EMAIL) VALUES ('Felipe', '2468', 1, 'Felipe', 'Montoya', 'felipe@correo.com');

INSERT INTO ROLES (NAME) VALUES ('ROLE_USER');
INSERT INTO ROLES (NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USERS_ROLES  (USER_ID, ROLES_ID) VALUES (1,1);
INSERT INTO USERS_ROLES  (USER_ID, ROLES_ID) VALUES (1,2);
INSERT INTO USERS_ROLES  (USER_ID, ROLES_ID) VALUES (2,1);
INSERT INTO USERS_ROLES  (USER_ID, ROLES_ID) VALUES (2,2);