INSERT INTO USERS (USERNAME,PASSWORD,ENABLED,NAME,LASTNAME,EMAIL) VALUES ('Admin', '$2a$10$7cCHdorngQIAX3QvnV95zO.1vsb0bN9/Cxv7dnAdBeUMAGhqtL86u', 1, 'Andres', 'Montoya', 'andres@correo.com');
INSERT INTO USERS (USERNAME,PASSWORD,ENABLED,NAME,LASTNAME,EMAIL) VALUES ('Andres', '$2a$10$7cCHdorngQIAX3QvnV95zO.1vsb0bN9/Cxv7dnAdBeUMAGhqtL86u', 1, 'Felipe', 'Montoya', 'felipe@correo.com');

INSERT INTO ROLES (NAME) VALUES ('ROLE_USER');
INSERT INTO ROLES (NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USERS_ROLES  (USER_ID, ROLES_ID) VALUES (1,1);
INSERT INTO USERS_ROLES  (USER_ID, ROLES_ID) VALUES (1,2);
INSERT INTO USERS_ROLES  (USER_ID, ROLES_ID) VALUES (2,1);
